apiVersion: v1
kind: Secret
metadata:
  name: my-secret-tls
  namespace: default

secretGenerator:
- name: my-apps-sec
  #literals:
  #- password=YOUR_PASSWORD
  #files:
  #- username.txt
  #- password.txt
  envs:
  - .env.secret
---
apiVersion: v1
kind: Secret
resources:
  - k8s-ingress.yaml
  - k8s-mysql.yaml
  - k8s-pv.yaml
  - k8s-tls.yaml
  - k8s-wordpress.yaml